In [33]:
import torch
import torch.nn as nn

In [34]:
inputs = torch.rand((4,5))
inputs

tensor([[0.5023, 0.3515, 0.3002, 0.4263, 0.8637],
        [0.4648, 0.2381, 0.3798, 0.0939, 0.4562],
        [0.7456, 0.7410, 0.2649, 0.2217, 0.0123],
        [0.3649, 0.6121, 0.8657, 0.8233, 0.4018]])

In [35]:
neighbors = torch.Tensor([
    [0,1],
    [1,2],
    [2,3],
    [0,4],
]).long()
neighbors

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [0, 4]])

In [53]:
idx = torch.Tensor([0,1,2,3,4]).unsqueeze(0).expand(inputs.shape)
idx

tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]])

In [36]:
inputs.shape, neighbors.shape

(torch.Size([4, 5]), torch.Size([4, 2]))

In [37]:
inputs[:,[2,3]]

tensor([[0.3002, 0.4263],
        [0.3798, 0.0939],
        [0.2649, 0.2217],
        [0.8657, 0.8233]])

In [38]:
for i, x in enumerate(neighbors):
    print(inputs[i][x])
    inputs[i][x] = torch.zeros(inputs[i][x].shape)

tensor([0.5023, 0.3515])
tensor([0.2381, 0.3798])
tensor([0.2649, 0.2217])
tensor([0.3649, 0.4018])


In [39]:
inputs

tensor([[0.0000, 0.0000, 0.3002, 0.4263, 0.8637],
        [0.4648, 0.0000, 0.0000, 0.0939, 0.4562],
        [0.7456, 0.7410, 0.0000, 0.0000, 0.0123],
        [0.0000, 0.6121, 0.8657, 0.8233, 0.0000]])

In [40]:
inputs

tensor([[0.0000, 0.0000, 0.3002, 0.4263, 0.8637],
        [0.4648, 0.0000, 0.0000, 0.0939, 0.4562],
        [0.7456, 0.7410, 0.0000, 0.0000, 0.0123],
        [0.0000, 0.6121, 0.8657, 0.8233, 0.0000]])

In [42]:
inputs[i][x]

tensor([0., 0.])

In [54]:
idx[~idx.unsqueeze(1).eq(neighbors).all(-1).any(-1)]

RuntimeError: The size of tensor a (5) must match the size of tensor b (2) at non-singleton dimension 2